dataSourceName: h2
addTestCustomers: true
# Database settings.
database:
  driverClass: org.h2.Driver
  # the username
  user: customerManager
  # the password
  password: customerManager
  # the JDBC URL; the database is called DWGettingStarted
  url: jdbc:h2:~/customers
